### ISSUE TITLE
500

### ISSUE THREAD

**Issue by Cyl18** [Cyl18/CFPABot#2]
```log
cfpabot_1  | fail: Microsoft.AspNetCore.Server.Kestrel[13]
cfpabot_1  |       Connection id "0HMG8T02ACJ25", Request id "0HMG8T02ACJ25:00000002": An unhandled exception was thrown by the application.
cfpabot_1  |       System.Net.Http.HttpRequestException: The SSL connection could not be established, see inner exception.
cfpabot_1  |        ---> System.IO.IOException: Unable to read data from the transport connection: Connection reset by peer.
cfpabot_1  |        ---> System.Net.Sockets.SocketException (104): Connection reset by peer
cfpabot_1  |          --- End of inner exception stack trace ---
cfpabot_1  |          at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
cfpabot_1  |          at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.GetResult(Int16 token)
cfpabot_1  |          at System.Net.Security.SslStream.<FillHandshakeBufferAsync>g__InternalFillHandshakeBufferAsync|182_0[TIOAdapter](TIOAdapter adap, ValueTask`1 task, Int32 minSize)
cfpabot_1  |          at System.Net.Security.SslStream.ReceiveBlobAsync[TIOAdapter](TIOAdapter adapter)
cfpabot_1  |          at System.Net.Security.SslStream.ForceAuthenticationAsync[TIOAdapter](TIOAdapter adapter, Boolean receiveFirst, Byte[] reAuthenticationData, Boolean isApm)
cfpabot_1  |          at System.Net.Http.ConnectHelper.EstablishSslConnectionAsyncCore(Boolean async, Stream stream, SslClientAuthenticationOptions sslOptions, CancellationToken cancellationToken)
cfpabot_1  |          --- End of inner exception stack trace ---
cfpabot_1  |          at System.Net.Http.ConnectHelper.EstablishSslConnectionAsyncCore(Boolean async, Stream stream, SslClientAuthenticationOptions sslOptions, CancellationToken cancellationToken)
cfpabot_1  |          at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
cfpabot_1  |          at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
cfpabot_1  |          at System.Net.Http.HttpConnectionPool.GetHttpConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
cfpabot_1  |          at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
cfpabot_1  |          at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
cfpabot_1  |          at System.Net.Http.DiagnosticsHandler.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
cfpabot_1  |          at System.Net.Http.HttpClient.SendAsyncCore(HttpRequestMessage request, HttpCompletionOption completionOption, Boolean async, Boolean emitTelemetryStartStop, CancellationToken cancellationToken)
cfpabot_1  |          at System.Net.Http.HttpClient.GetStringAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken)
cfpabot_1  |          at CFPABot.Utils.GitHub.Diff(Int32 id) in /src/CFPABot/Utils/GitHub.cs:line 50
cfpabot_1  |          at CFPABot.Controllers.CompareController.GenRadios(Int32 prid, String modid, String modDomain) in /src/CFPABot/Controllers/CompareController.cs:line 117
cfpabot_1  |          at CFPABot.Controllers.CompareController.PRA(String pr, String modid, String modDomain) in /src/CFPABot/Controllers/CompareController.cs:line 64
cfpabot_1  |          at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
cfpabot_1  |          at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
cfpabot_1  |          at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
cfpabot_1  |          at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
cfpabot_1  |          at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
cfpabot_1  |          at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
cfpabot_1  |          at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
cfpabot_1  |          at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
cfpabot_1  |          at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
cfpabot_1  |          at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
cfpabot_1  |          at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)
```

```
cfpabot_1  | System.IO.IOException: The process cannot access the file '/app/temp/emt-12.4.1.jar' because it is being used by another process.
cfpabot_1  |    at System.IO.FileStream.Init(FileMode mode, FileShare share, String originalPath)
cfpabot_1  |    at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
cfpabot_1  |    at CFPABot.Utils.CurseManager.GetModLangFiles(String downloadUrl, LangType type) in /src/CFPABot/Utils/CurseManager.cs:line 207
cfpabot_1  |    at CFPABot.Controllers.CompareController.GenRadios(Int32 prid, String modid, String modDomain) in /src/CFPABot/Controllers/CompareController.cs:line 188
cfpabot_1  | System.IO.IOException: The process cannot access the file '/app/temp/EMT-B_EMT4.5.jar' because it is being used by another process.
cfpabot_1  |    at System.IO.FileStream.Init(FileMode mode, FileShare share, String originalPath)
cfpabot_1  |    at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
cfpabot_1  |    at CFPABot.Utils.CurseManager.GetModLangFiles(String downloadUrl, LangType type) in /src/CFPABot/Utils/CurseManager.cs:line 207
cfpabot_1  |    at CFPABot.Controllers.CompareController.GenRadios(Int32 prid, String modid, String modDomain) in /src/CFPABot/Controllers/CompareController.cs:line 188
cfpabot_1  | System.IO.IOException: The process cannot access the file '/app/temp/EMT-alpha2.0_without-lore_and_recipes.jar' because it is being used by another process.
cfpabot_1  |    at System.IO.FileStream.Init(FileMode mode, FileShare share, String originalPath)
cfpabot_1  |    at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
cfpabot_1  |    at CFPABot.Utils.CurseManager.GetModLangFiles(String downloadUrl, LangType type) in /src/CFPABot/Utils/CurseManager.cs:line 207
cfpabot_1  |    at CFPABot.Controllers.CompareController.GenRadios(Int32 prid, String modid, String modDomain) in /src/CFPABot/Controllers/CompareController.cs:line 188
```

**Comment by n0099** [comment]
建议自动retry
